### ISSUE TITLE
Import error (partly?)

### ISSUE THREAD

**Issue by DerekX** [CruzR/Blender-MDL#13]
Warcraft 3 models load, but with this error:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.63\s
cripts\addons\WarMDLImport.py", line 324, in execute
    return di.run(self.filepath, context)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.63\s
cripts\addons\WarMDLImport.py", line 290, in run
    texface.uv1 = (self.mgr.tvertices[i][face[0]][0], 1 - self.mgr.tvertices[i][
face[0]][1])
AttributeError: 'MeshTexturePoly' object has no attribute 'uv1'

**Comment by CruzR** [comment]
Well, I haven't done any work on this project for some time, and from your error message it seems that the Blender Python API has slightly changed. If I find the time I'll look into it.

**Comment by CruzR** [comment]
Huh, it seems the Blender Python API documentation is getting worse with each release. It might take some time to digg into this issue.

**Comment by DerekX** [comment]
Take yer time man. I got other stuff going on, and I'd rather get this right.

**Comment by CruzR** [comment]
Alright, I think it should be fixed now. Could you please confirm that?

**Comment by DerekX** [comment]
Confirmed. Error's gone and the textures also load correctly. :)

**Comment by CruzR** [comment]
Great! I'll close this issue.
